# Generated by Django 2.2 on 2019-04-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(default='Masculino', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(default=1)),
                ('nombre_apellido', models.CharField(default='Juan Roman Riquelme', max_length=200)),
                ('email', models.CharField(default='roman@moni.com.ar', max_length=200)),
                ('monto', models.IntegerField(blank=True, default=1, null=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.Genero')),
            ],
        ),
    ]
