# Generated by Django 2.2 on 2019-04-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='email',
            field=models.EmailField(default='roman@moni.com.ar', max_length=200),
        ),
    ]
